sonar.projectKey=monapp
sonar.working.directory=C:\\labs\\monapp\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\labs\\monapp
sonar.pullrequest.cache.basepath=C:\\labs\\monapp
sonar.sources=\
"C:\\labs\\monapp\\charts\\monapp\\Chart.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\values.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\deployment.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\hpa.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\httproute.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\ingress.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\service.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\serviceaccount.yaml",\
"C:\\labs\\monapp\\charts\\monapp\\templates\\tests\\test-connection.yaml",\
"C:\\labs\\monapp\\Dockerfile",\
"C:\\labs\\monapp\\global.json"

1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.projectKey=monapp:1F3D632E-17B0-A83C-978B-66083B28DA2D
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.projectName=MonApp.Api
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.projectBaseDir=C:\\labs\\monapp\\src\\MonApp.Api
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.sourceEncoding=utf-8
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.tests=
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.sources=\
"C:\\labs\\monapp\\src\\MonApp.Api\\Program.cs",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\MonApp.Api.GlobalUsings.g.cs",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\MonApp.Api.AssemblyInfo.cs",\
"C:\\labs\\monapp\\src\\MonApp.Api\\appsettings.Development.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\appsettings.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\MonApp.Api.http",\
"C:\\labs\\monapp\\src\\MonApp.Api\\Properties\\launchSettings.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\MonApp.Api.csproj.nuget.dgspec.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\project.assets.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\bin\\Debug\\net10.0\\MonApp.Api.deps.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\bin\\Debug\\net10.0\\MonApp.Api.runtimeconfig.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\bin\\Debug\\net10.0\\MonApp.Api.staticwebassets.endpoints.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\MonApp.Api.sourcelink.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\labs\\monapp\\src\\MonApp.Api\\obj\\Debug\\net10.0\\staticwebassets.build.json"

1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.cs.analyzer.projectOutPaths=\
"C:\\labs\\monapp\\.sonarqube\\out\\0"
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.cs.roslyn.reportFilePaths=\
"C:\\labs\\monapp\\.sonarqube\\out\\0\\Issues.json"
1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.cs.scanner.telemetry=\
"C:\\labs\\monapp\\.sonarqube\\out\\0\\Telemetry.json"

1F3D632E-17B0-A83C-978B-66083B28DA2D.sonar.working.directory=C:\\labs\\monapp\\.sonarqube\\out\\.sonar\\mod0
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.projectKey=monapp:3E434451-E1E2-9A7D-36F9-116D7DB9C35C
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.projectName=MonApp.Tests
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.projectBaseDir=C:\\labs\\monapp\\tests\\MonApp.Tests
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.sourceEncoding=utf-8
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.sources=
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.tests=\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\obj\\MonApp.Tests.csproj.nuget.dgspec.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\obj\\project.assets.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\MonApp.Api.deps.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\MonApp.Api.runtimeconfig.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\MonApp.Api.staticwebassets.endpoints.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\MonApp.Tests.deps.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\MonApp.Tests.runtimeconfig.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\bin\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\obj\\Debug\\net10.0\\MonApp.Tests.sourcelink.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\obj\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\UnitTest1.cs",\
"C:\\labs\\monapp\\tests\\MonApp.Tests\\TestResults\\080b2b19-9dff-42f9-9133-75c8313a66f3\\coverage.opencover.xml"

3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.cs.analyzer.projectOutPaths=\
"C:\\labs\\monapp\\.sonarqube\\out\\1"
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.cs.roslyn.reportFilePaths=\
"C:\\labs\\monapp\\.sonarqube\\out\\1\\Issues.json"
3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.cs.scanner.telemetry=\
"C:\\labs\\monapp\\.sonarqube\\out\\1\\Telemetry.json"

3E434451-E1E2-9A7D-36F9-116D7DB9C35C.sonar.working.directory=C:\\labs\\monapp\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.qualitygate.wait=true
sonar.exclusions=**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=1F3D632E-17B0-A83C-978B-66083B28DA2D,3E434451-E1E2-9A7D-36F9-116D7DB9C35C

